### ISSUE TITLE
java.lang.IllegalStateException: globalInitialize is not called yetのエラー

### ISSUE THREAD

**Issue by imagepit** [SahaginOrg/japanese-forum#1]
Androidのテスト自動化のために、appiumにsahagin0.8.2を取り入れてjenkinsでレポート出力したいと思っています。

環境

Mac OX 10.11.3
Andriod Studio 1.5.1
Gradle 2.8

sahagin0.8.2をbuild.gradleに追加して、

```
dependencies {
    :
    :
    testCompile 'org.sahagin:sahagin:0.8.2'
}
```

テストクラスに初期処理で下記のコードを追加したのですがエラーが発生します。

```
driver = new AndroidDriver(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);
AppiumAdapter.setAdapter(driver);
```

キャプチャを取りましたのでご確認ください。

![](https://www.evernote.com/l/AB15FrXbPtNM_aDZQD0HQrJFJwvoT694fEgB/image.png0)

```
java.lang.IllegalStateException: globalInitialize is not called yet
```

おそらくですが、0.8.2のソースではAdapterContainer.javaが最新でなく、必ずglobalInstanceメソッドでエラーが出るのではと考えています。
※Githubの最新のソースコードでは該当箇所は2015年12月に修正されているようです。

ご確認お願いします。

**Comment by NozomiIto** [comment]
こちらですが、Gradleでの必要な[セットアップ手順](http://blog.trident-qa.com/2015/01/sahagin-first-release-2/#sec2-1)のうち、build.gradleに以下のコードを追加する作業が不足しているため起きているのではないかと思います。

``` groovy
def sahaginVersion = '0.8.2'

test {
    doFirst {
        // ローカルキャッシュからsahaginのJarファイルを検索
        def sahaginJar = project.configurations.testCompile.find {
            it.name == 'sahagin-' + sahaginVersion + '.jar'
        }
        jvmArgs '-javaagent:' + sahaginJar
    }
}
```

こちらを行った上でgradleからテストを実行すれば、レポートが生成されるのではないかと思うので、試してみてもらえますでしょうか。

ちなみに[2015年12月の修正](https://github.com/SahaginOrg/sahagin-java/commit/4b17cc5e79b987a4048dc0776e6ffed8ab848cfb)は、このJVM引数をつけずに実行した場合でもエラーにせず、警告メッセージを出してテストを実行するようにしたものです(この場合Sahaginレポートは生成されません)。
JVM引数の有無でSahagin利用の有無を簡単に切り替えられるようにこの機能を実装しました。

**Comment by imagepit** [comment]
ご連絡ありがとうございます。
build.gradleにご指定のものを追加してsyncすると下記のようにエラーがでてしまいます。
私あまりgradleのことを知らないのですが、test()が認識していないようです。

![](https://www.evernote.com/l/AB3MvWK05rxDT7aGUhjQ32bTwGAA9Qf6nQIB/image.png)

**Comment by NozomiIto** [comment]
Android上でのgradle実行でtestタスクがうまく認識されていないような気がします。

参考: http://stackoverflow.com/questions/31275976/gradle-dsl-method-not-found-test

build.gradle上の、`apply plugin: 'java'`などのapply pluginの処理はどう書かれているでしょうか?

**Comment by NozomiIto** [comment]
http://stackoverflow.com/questions/31275976/gradle-dsl-method-not-found-test
によれば

``` groovy
def sahaginVersion = '0.8.2'

tasks.withType(Test) {
    doFirst {
        // ローカルキャッシュからsahaginのJarファイルを検索
        def sahaginJar = project.configurations.testCompile.find {
            it.name == 'sahagin-' + sahaginVersion + '.jar'
        }
        jvmArgs '-javaagent:' + sahaginJar
    }
}
```

で動くかもしれません。

**Comment by imagepit** [comment]
ありがとうございます。上記のコードに変えたらsyncが通るようになりました。
しかし、テスト実行してもやはり`AppiumAdapter.setAdapter(driver);`で同様のエラーが出てしまいます。。

![](https://www.evernote.com/l/AB1IKxL1R3RAkrIhve7kkpnaF827cHuDs7EB/image.png)

**Comment by NozomiIto** [comment]
すみません、私もAndroid Studioは不慣れ & SahaginをAndroid Studioで使うのは初挑戦なのですが、Gradleからのテスト実行ではなく、クラスを直接JUnit実行しているからだと思います。

とりあえず[こちら](https://github.com/mixi-inc/AndroidTraining/wiki/1.05.-Android-%E3%81%AE%E3%83%93%E3%83%AB%E3%83%89%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6%EF%BC%88Gradle%EF%BC%89#%E5%AE%9F%E8%A1%8C)の方法でAndroid Studio上で「./gradlew test」を実行したら動きました。(Android StudioのGradleウィンドウからtestタスクを実行するなど他の方法もあるようなんですが、ちょっと手元でうまく動かせていません)

これが、うまくいけばsahagin.ymlが見つからないというエラーがでるかもしれません。その場合は[こちら](http://blog.trident-qa.com/2015/01/sahagin-first-release-2/#sec2-4)のようにsahagin.ymlを置いていただく必要があります。

**Comment by imagepit** [comment]
ありがとうございます。ご指摘のとおり、sahagin.yumをappディレクトリに作成し、`./gradlew test`をコマンドで実行したら無事レポートが出力されました！！
コマンドで実行できればjenkinsでレポートを表示させる事ができるので私はこちらで十分です。
本当にサポートして頂きありがとうございました。

**Comment by NozomiIto** [comment]
よかったです！ぜひご活用ください。

JVM引数まわりはどうもトラブるケースが多いようなので、そのうち不要にできるよう頑張ります！
