### ISSUE TITLE
Windowsでユーザー名に漢字が含まれているとSeleniumが立ち上がった瞬間に停止する問題

### ISSUE THREAD

**Issue by sleepless-se** [SahaginOrg/japanese-forum#2]
初めまして、Noriと申します。
`[ブログ](http://blog.trident-qa.com/2016/03/sahagin-japanese-forum/)`を読ませてもらいこちらの問い合わせフォーラムを知りました。

以前よりJavaで作ったSeleniumのプログラムを複数のユーザーに配布し利用しています。
そこで、よくある問題としてユーザー名に漢字が含まれているとSeleniumが立ち上がった瞬間に停止する問題です。

今手元にエラーログがなくて申し訳ないのですが、起動時にプロファイルを読みに行こうとしたところで感じが文字化けし、プロファイルを読み込めずnullが出てSeleniumが停止します。

現在はユーザーにWindowsで漢字を含まない新規ユーザーを作ってもらうことで対応してもらっていますが、毎回これをするのは手間ですしアカウントを切り替える手間もあり、ユーザーの負担も大きいです。

もし、可能でしたらこの部分のアップデートをお願いできればと思います。
大変恐縮ではございますがよろしくお願い致します。

**Comment by NozomiIto** [comment]
初めまして。Noriさん。
プロファイルというのはFirefoxのプロファイルでしょうか?どのブラウザで発生するのでしょうか?

また、Selenium + Sahagin を利用していてこのエラーが起きるのでしょうか?
SahaginではなくSeleniumに関するお問い合わせに見えましたので。

**Comment by NozomiIto** [comment]
https://groups.google.com/d/msg/seleniumjp/K4fseNoo3JU/5oluDKDxAQAJ
おそらくFirefoxDriverの問題で、こちらの投稿の方法で回避できると思います。
