### ISSUE TITLE
java-client 5.0.0のサポートについて

### ISSUE THREAD

**Issue by ageishi** [SahaginOrg/japanese-forum#4]
appiumのレポート出力に利用させて頂いております。
先日appiumのjava-clientの5.0.0がリリースされましたが、Sahaginを組み込んでいると
テスト実行時にエラーになります。
java-client 4.1.2では動作しています。

私の設定が悪いか確認させて下さい。
エラーとpomを添付致します。
pomはjava-clientのバージョンを4.1.12→5.0.1に編集しました。

**環境**
- Appium version (or git revision) that exhibits the issue: 1.6.5
- Desktop OS/version used to run Appium: Mac 10.12.5
- Node.js version (unless using Appium.app|exe): v7.10.0
- Mobile platform/version under test: Android 6.0.1
- Real device or emulator/simulator: ASUS_Z01FD
- Appium CLI or Appium.app|exe: Appium CLI / Appium.app
- Sahagin: 0.9.2
- JDK: 1.8.0_144

エラー
[errorLog.txt](https://github.com/SahaginOrg/japanese-forum/files/1269015/errorLog.txt)

pom
[pom.txt](https://github.com/SahaginOrg/japanese-forum/files/1269016/pom.txt)

**Comment by NozomiIto** [comment]
@ageishi 反応が大変遅くすみません。

```
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /Volumes/SVN/appium/sample-code/sample-code/examples/java/junit && /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/bin/java -javaagent:/Users/age2/.m2/repository/org/sahagin/sahagin/0.9.2/sahagin-0.9.2.jar -jar /Volumes/SVN/appium/sample-code/sample-code/examples/java/junit/target/surefire/surefirebooter6629876876875155404.jar /Volumes/SVN/appium/sample-code/sample-code/examples/java/junit/target/surefire 2017-09-01T11-15-40_858-jvmRun1 surefire774447133094811265tmp surefire_07377849975160098281tmp
```

このあたりが問題のようですね。

さきほど、最新のソース(Selenium3+Java8対応)をjar化しました。sahagin-javaのバージョンを`0.9.2.99-RELEASE-CANDIDATE`にするとこれが使用できますが、こちらでもやはり動かないでしょうか?

**Comment by NozomiIto** [comment]
> 私の設定が悪いか確認させて下さい。

設定が悪いということは特にないように思います。Sahaginを除外すればjava-client 5.0.1でも動くのであれば、何かsahaginの問題の可能性があります。

こちらの環境で少し試した限りでは、sahagin-java : 0.9.2.99-RELEASE-CANDIDATE とjava-client: 5.0.1の組み合わせでAppiumDriverを生成しても、上記のようなクラッシュは起きませんでした。

**Comment by ageishi** [comment]
こちらこそ確認が遅くなり、すみません。

sahagin-java : 0.9.2.99-RELEASE-CANDIDATE とjava-client: 5.0.1の組み合わせで動作することを確認できました。

ご対応頂きありがとうございました。

**Comment by NozomiIto** [comment]
よかったです！後日正式版としてリリースいたします。

**Comment by NozomiIto** [comment]
正式版として[0.10.1](https://github.com/SahaginOrg/japanese-forum/releases/tag/0.10.1)をリリースしました。
